language: php
sudo: required
dist: trusty

addons:
  hosts:
    - commander.test
  firefox: "35.0.1"
  postgresql: "9.3"
  apt:
    packages:
      - oracle-java9-installer
      - oracle-java9-set-default
      - redis-server

services:
  - redis-server

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

# Alternate tests with MySQL and PostgreSQL
matrix:
  include:
    # PHP 7.0
    - php: 7.0
      env: DB=pgsql  MOODLE_BRANCH=MOODLE_33_STABLE
    - php: 7.0
      env: DB=mysqli MOODLE_BRANCH=MOODLE_34_STABLE

before_install:
  - export MOODLE_VERSION=$(echo "$MOODLE_BRANCH" | cut -d'_' -f 2)
  - if [ "$MOODLE_VERSION" = "master" ] || [ "$MOODLE_VERSION" -ge 32 ]; then export CI=2; else export CI=1; fi
  - echo $CI
  - phpenv config-rm xdebug.ini
  - cd ../..
  - nvm install 8.9;
    nvm use 8.9;
    composer create-project -n --no-dev --prefer-dist moodlerooms/moodle-plugin-ci ci ^2;
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install -vvv
  - echo '$CFG->cookiesecure = false;' >> moodle/config.php

script:
  - moodle-plugin-ci validate
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci savepoints
  - moodle-plugin-ci mustache
  - moodle-plugin-ci grunt
  - moodle-plugin-ci phpunit
  - moodle-plugin-ci behat